services:
  - type: web
    name: pdf-drop-processor
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ADOBE_CREDS_PATH
        sync: false
